export const TOGGLEMAILNAV = 'TOGGLEMAILNAV';
export const AREACHARGE = 'AREACHARGE';

export const LOADING_LOGIN = 'LOADING_LOGIN';
export const LOADING_SIGNUP = 'LOADING_SIGNUP';
export const SET_USER = 'SET_USER';
export const ERRORMESSAGE="ERRORMESSAGE";
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const START_LOADING_APP = 'START_LOADING_APP';
export const STOP_LOADING_APP = 'STOP_LOADING_APP';
export const SELECT_UNIT = 'SELECT_UNIT';
export const REMOVE_UNIT = 'REMOVE_UNIT';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const REMOVE_DEPARTMENT = 'REMOVE_DEPARTMENT';
export const FORWARD ='FORWARD'
